import { IPersonAssignmentList } from "./personAssignmentList";

export const data: IPersonAssignmentList[] = [
  {
    day: new Date(2023, 0, 25),
    nameMicroG: "Elie bhizende",
    nameMicroD: "Chris Clares",
    microPodium: "Rachid Ouarmina",
    usher: "Brian Teka Sala",
    sono: "Josuel Fanuel",
  },
  {
    day: new Date(2023, 0, 29),
    nameMicroG: "Jeff De Clerck",
    nameMicroD: "Gilles Merciny",
    microPodium: "Jules De Clerck",
    usher: "Elie Bihzende",
    sono: "Owen Nkosi Sala",
  },
  {
    day: new Date(2023, 1, 1),
    nameMicroG: "Owen Nkosi Sala",
    nameMicroD: "jules De Clerck",
    microPodium: "Adje Wilson",
    usher: "Gilles Merciny",
    sono: "Brian Teka Sala",
  },
  {
    day: new Date(2023, 1, 5),
    nameMicroG: "rachid ouarmina",
    nameMicroD: "Jeff de Clerck",
    microPodium: "Josue Fanuel",
    usher: "Owen Nkosi Sala",
    sono: "Gilles Merciny",
  },
  {
    day: new Date(2023, 1, 8),
    nameMicroG: "Jules de Clerck",
    nameMicroD: "Elie Bhizende",
    microPodium: "Owen Nkosi Sala",
    usher: "Gilles Merciny",
    sono: "Rachid Ourmina",
  },
  {
    day: new Date(2023, 1, 12),
    nameMicroG: "Brian Teka Sala",
    nameMicroD: "Adje wilson",
    microPodium: "Gilles Merciny",
    usher: "Jules De Clerck",
    sono: "Jeff De Clerck",
  },
  {
    day: new Date(2023, 1, 15),
    nameMicroG: "Josue Fanuel",
    nameMicroD: "Owen Nkosi Sala",
    microPodium: "Elie bihzende",
    usher: "rachid ouarmina",
    sono: "Brian Teka Sala",
  },
  {
    day: new Date(2023, 1, 19),
    nameMicroG: "Adje Wilson",
    nameMicroD: "Chris Clares",
    microPodium: "Jules De Clerck",
    usher: "Brian Teka Sala",
    sono: "Jeff de Clerck",
  },
  {
    day: new Date(2023, 1, 22),
    nameMicroG: "Brian teka sala",
    nameMicroD: "owen Nkosi Sala",
    microPodium: "Gilles Merciny",
    usher: "jeff de clerck",
    sono: "rachid ouarmina",
  },
];
